repos:
-   repo: https://git.webwave.work/Common/git-naming-hooks.git
    rev: ea0e9a7d05a07c149acbf6edc3dcd17014e802cd
    hooks:
    -   id: check-git-commit
        args: [--py38-plus, --add-import, 'from __future__ import annotations']
    -   id: check-git-branch