repos:
-   repo: https://git.webwave.work/Common/git-naming-hooks.git
    rev: 650021122a3728edf869762633fedffde65f4cd7
    hooks:
    -   id: check-git-commit
    -   id: check-git-branch
        args: [-r, '^(AGG|Agg|agg)-[0-9]+((_|\/)[\w\-_]+)?']