repos:
-   repo: https://git.webwave.work/Common/git-naming-hooks.git
    rev: 3efe60a045e2afb83b2e081dcd438a8a43daf257
    hooks:
    -   id: check-git-commit
        args: [-r, '^test2?']
    -   id: check-git-branch
        args: [-r, '^test2?']