repos:
-   repo: https://git.webwave.work/Common/git-naming-hooks.git
    rev: 7511c67575ec39ea239c34b22219478ff2bf14c6
    hooks:
    -   id: check-git-commit
    -   id: check-git-branch
        args: [-r, '^(AGG|Agg|agg)-[0-9]+((_|\/)[\w\-_]+)?']